name: TimerPlus
author: killer549
version: 1.0.0
api: [3.0.0-ALPHA12]
description: Timer plugin
main: killer549\timerplus\timerplus
commands:
    stimer:
        description: Starts the timer
        permission: TimerPlus.command.stimer
permissions:
    TimerPlus.command.stimer:
        default: true
        description: Starts the timer
